title: Sydney Games Festival 2026
description: A community-run games festival for Sydney.
url: "https://sydneygamesfestival.org"
baseurl: ""
markdown: kramdown

collections:
  faqs:
    output: false
  organisations:
    output: false

# GitHub Pages does not need any custom plugins for this site.
